name: Build & Publish Docker Image

on:
  push:
    branches: [main]

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}

    - name: Build Docker image
      run: docker build -t ghcr.io/${{ github.repository_owner }}/image-1:latest .

    - name: Push Docker image
      run: docker push ghcr.io/${{ github.repository_owner }}/image-1:latest

    - name: Install GitHub CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y gh

    - name: Authenticate GitHub CLI
      run: echo "${{ secrets.CR_PAT }}" | gh auth login --with-token

    - name: Set package visibility to public
      run: |
        gh api --method PATCH \
          -H "Accept: application/vnd.github.v3+json" \
          /users/${{ github.repository_owner }}/packages/container/image-1/visibility \
          -f visibility=public
